version: "3.9"

services:
  # container for php-fpm
  php:
    image: php:fpm
    volumes:
      - ./code:/code
      - ./conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro
    networks:
      - code-network
    #  container for nginx webserver
  server:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code:ro
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
    depends_on:
      - php

  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ../databases/infrastruktur:/var/lib/mysql
    networks:
      - code-network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    networks:
      - code-network
    depends_on:
      - db

networks:
  code-network:
    driver: bridge
