version: "3.9"

services:
  # container for php-fpm
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php-fpm
    volumes:
      - ./app:/code
      - ./conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro
      - ./conf/php.ini:/usr/local/etc/php/php.init:ro
    networks:
      - task
    restart: unless-stopped
    depends_on:
      - db

  server:
    image: nginx:latest
    container_name: server
    ports:
      - ${NGINX}:80
    volumes:
      - ./app:/code
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - task
    depends_on:
      - php

  db:
    image: mysql
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    volumes:
      - ../databases/infrastruktur:/var/lib/mysql
    networks:
      - task

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - task
    volumes:
      - ./app/redis-data:/data

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER}:8080
    networks:
      - task
    depends_on:
      - db

networks:
  task:
    driver: bridge
